// ============================================================
// MOCK DATA — Halal Certification App
// All data is static/hardcoded for the mockup
// ============================================================

export const workspace = {
  id: "ws-001",
  name: "Nasi Lemak Sdn Bhd",
  plan: "Pro",
  createdAt: "2023-06-15",
};

// ── COMPANY ─────────────────────────────────────────────────
export const company = {
  id: "comp-001",
  name: "Nasi Lemak Sdn Bhd",
  registrationNo: "202301012345 (1234567-H)",
  ssmNo: "202301012345",
  businessType: "Food & Beverage",
  address: "No. 12, Jalan Bukit Bintang, 55100 Kuala Lumpur, Wilayah Persekutuan",
  contactPerson: "Ahmad Faris bin Abdullah",
  phone: "+603-2145 6789",
  email: "admin@nasilemaksb.com.my",
  website: "www.nasilemaksb.com.my",
  businessCategory: "Food Premises & F&B Products",
  businessSize: "Small",
  establishedYear: 2023,
  myeHalalRef: "MYH-2023-00512",
};

// ── LOCATIONS ───────────────────────────────────────────────
export const locations = [
  {
    id: "loc-001",
    name: "Main Outlet – Bukit Bintang",
    type: "Outlet",
    address: "No. 12, Jalan Bukit Bintang, 55100 Kuala Lumpur",
    city: "Kuala Lumpur",
    state: "Wilayah Persekutuan",
    operatingStartDate: "2023-06-15",
    localAuthorityLicence: "DBL-WP-2023-0889",
    foodPremiseReg: "FPR-WP-2023-3301",
    employeeCount: 12,
    menuCount: 8,
    readinessScore: 82,
    status: "Active",
    applications: ["APP-001"],
  },
  {
    id: "loc-002",
    name: "Central Kitchen – Petaling Jaya",
    type: "Central Kitchen",
    address: "Lot 7, Jalan Kemajuan, Seksyen 13, 46200 Petaling Jaya, Selangor",
    city: "Petaling Jaya",
    state: "Selangor",
    operatingStartDate: "2023-08-01",
    localAuthorityLicence: "DBL-SEL-2023-1122",
    foodPremiseReg: "FPR-SEL-2023-4477",
    employeeCount: 8,
    menuCount: 12,
    readinessScore: 68,
    status: "Active",
    applications: ["APP-002"],
  },
  {
    id: "loc-003",
    name: "Kiosk – KLCC",
    type: "Kiosk",
    address: "Lot G-14, Ground Floor, Suria KLCC, 50088 Kuala Lumpur",
    city: "Kuala Lumpur",
    state: "Wilayah Persekutuan",
    operatingStartDate: "2024-01-10",
    localAuthorityLicence: "DBL-WP-2024-0223",
    foodPremiseReg: "FPR-WP-2024-0991",
    employeeCount: 4,
    menuCount: 5,
    readinessScore: 55,
    status: "Active",
    applications: [],
  },
];

// ── EMPLOYEES ───────────────────────────────────────────────
export const employees = [
  {
    id: "emp-001",
    name: "Ahmad Faris bin Abdullah",
    icNo: "850312-14-5678",
    nationality: "Malaysian",
    status: "Muslim",
    employmentType: "Permanent",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    halalRole: "Halal PIC",
    certStatus: "Valid",
    certExpiry: "2025-12-31",
    foodHandlerCert: "Valid",
    typhoidVaccination: "Valid",
  },
  {
    id: "emp-002",
    name: "Siti Aisyah binti Mohd Yusof",
    icNo: "900605-10-1234",
    nationality: "Malaysian",
    status: "Muslim",
    employmentType: "Permanent",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    halalRole: "Halal Supervisor",
    certStatus: "Valid",
    certExpiry: "2025-06-30",
    foodHandlerCert: "Valid",
    typhoidVaccination: "Expiring Soon",
  },
  {
    id: "emp-003",
    name: "Muhammad Haziq bin Rosli",
    icNo: "951120-08-7890",
    nationality: "Malaysian",
    status: "Muslim",
    employmentType: "Permanent",
    locationId: "loc-002",
    locationName: "Central Kitchen – Petaling Jaya",
    halalRole: "Halal PIC",
    certStatus: "Valid",
    certExpiry: "2026-03-31",
    foodHandlerCert: "Valid",
    typhoidVaccination: "Valid",
  },
  {
    id: "emp-004",
    name: "Nurul Hidayah binti Kamarudin",
    icNo: "880417-03-4567",
    nationality: "Malaysian",
    status: "Muslim",
    employmentType: "Permanent",
    locationId: "loc-002",
    locationName: "Central Kitchen – Petaling Jaya",
    halalRole: "Halal Executive",
    certStatus: "Expiring Soon",
    certExpiry: "2025-03-15",
    foodHandlerCert: "Valid",
    typhoidVaccination: "Valid",
  },
  {
    id: "emp-005",
    name: "Lee Wei Ming",
    icNo: "920811-14-3456",
    nationality: "Malaysian",
    status: "Non-Muslim",
    employmentType: "Permanent",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    halalRole: null,
    certStatus: "N/A",
    certExpiry: null,
    foodHandlerCert: "Valid",
    typhoidVaccination: "Valid",
  },
  {
    id: "emp-006",
    name: "Rosmawati binti Hamid",
    icNo: "781234-05-6789",
    nationality: "Malaysian",
    status: "Muslim",
    employmentType: "Contract",
    locationId: "loc-003",
    locationName: "Kiosk – KLCC",
    halalRole: "Halal Supervisor",
    certStatus: "Valid",
    certExpiry: "2025-09-30",
    foodHandlerCert: "Expiring Soon",
    typhoidVaccination: "Valid",
  },
  {
    id: "emp-007",
    name: "Amirul Hakim bin Zainudin",
    icNo: "000215-11-2345",
    nationality: "Malaysian",
    status: "Muslim",
    employmentType: "Part-time",
    locationId: "loc-003",
    locationName: "Kiosk – KLCC",
    halalRole: null,
    certStatus: "N/A",
    certExpiry: null,
    foodHandlerCert: "Valid",
    typhoidVaccination: "Valid",
  },
  {
    id: "emp-008",
    name: "Priya Ramasamy",
    icNo: "870930-07-8901",
    nationality: "Malaysian",
    status: "Non-Muslim",
    employmentType: "Permanent",
    locationId: "loc-002",
    locationName: "Central Kitchen – Petaling Jaya",
    halalRole: null,
    certStatus: "N/A",
    certExpiry: null,
    foodHandlerCert: "Valid",
    typhoidVaccination: "Expired",
  },
];

// ── USERS & ROLES ────────────────────────────────────────────
export const users = [
  {
    id: "user-001",
    name: "Ahmad Faris bin Abdullah",
    email: "faris@nasilemaksb.com.my",
    role: "Owner",
    status: "Active",
    lastActive: "2025-02-20",
    avatarInitials: "AF",
  },
  {
    id: "user-002",
    name: "Nurul Hidayah binti Kamarudin",
    email: "hidayah@nasilemaksb.com.my",
    role: "Halal Executive",
    status: "Active",
    lastActive: "2025-02-19",
    avatarInitials: "NH",
  },
  {
    id: "user-003",
    name: "Siti Aisyah binti Mohd Yusof",
    email: "aisyah@nasilemaksb.com.my",
    role: "Application Manager",
    status: "Active",
    lastActive: "2025-02-18",
    avatarInitials: "SA",
  },
  {
    id: "user-004",
    name: "Lee Wei Ming",
    email: "weiming@nasilemaksb.com.my",
    role: "Viewer",
    status: "Active",
    lastActive: "2025-02-15",
    avatarInitials: "LW",
  },
  {
    id: "user-005",
    name: "Razman bin Sulaiman",
    email: "razman.consultant@halalpro.com.my",
    role: "Consultant",
    status: "Invited",
    lastActive: null,
    avatarInitials: "RS",
  },
];

// ── SUPPLIERS ───────────────────────────────────────────────
export const suppliers = [
  {
    id: "sup-001",
    name: "Delima Spices & Herbs Sdn Bhd",
    registrationNo: "202001045678",
    contactPerson: "Zulkifli bin Ahmad",
    email: "sales@delimaspices.com.my",
    phone: "+603-5566 7788",
    address: "Lot 23, Jalan Industri, Kawasan Perindustrian Balakong, 43300 Seri Kembangan, Selangor",
    suppliedIngredients: ["Rempah Nasi Lemak", "Cili Boh", "Serai Powder"],
    halalCertNo: "JAKIM/CERT/2022/001234",
    halalCertBody: "JAKIM",
    certStatus: "Valid",
    certExpiry: "2025-12-31",
    riskLevel: "Low",
  },
  {
    id: "sup-002",
    name: "Puncak Dairy Industries Sdn Bhd",
    registrationNo: "200301098765",
    contactPerson: "Chong Mei Ling",
    email: "procurement@puncakdairy.com.my",
    phone: "+603-3344 5566",
    address: "Jalan Puncak, 68000 Ampang, Selangor",
    suppliedIngredients: ["Santan Segar", "Santan UHT"],
    halalCertNo: "JAKIM/CERT/2023/005678",
    halalCertBody: "JAKIM",
    certStatus: "Valid",
    certExpiry: "2026-06-30",
    riskLevel: "Low",
  },
  {
    id: "sup-003",
    name: "Global Food Ingredients Bhd",
    registrationNo: "199801023456",
    contactPerson: "Raj Kumar",
    email: "info@globalfood.com.my",
    phone: "+603-7788 9900",
    address: "No. 5, Jalan Teknologi, Taman Sains Selangor, 47810 Petaling Jaya, Selangor",
    suppliedIngredients: ["Perisa Pandan", "Pewarna Makanan", "Stabiliser E471"],
    halalCertNo: "JAKIM/CERT/2021/009876",
    halalCertBody: "JAKIM",
    certStatus: "Expired",
    certExpiry: "2024-12-31",
    riskLevel: "High",
  },
  {
    id: "sup-004",
    name: "Mulia Rice Mill Sdn Bhd",
    registrationNo: "201501067890",
    contactPerson: "Mohd Hanif bin Idris",
    email: "orders@muliarice.com.my",
    phone: "+603-8899 1122",
    address: "KM 12, Jalan Sungai Buloh, 47000 Sungai Buloh, Selangor",
    suppliedIngredients: ["Beras Basmati", "Beras Tempatan"],
    halalCertNo: "JAKIM/CERT/2024/003344",
    halalCertBody: "JAKIM",
    certStatus: "Valid",
    certExpiry: "2026-03-31",
    riskLevel: "Low",
  },
  {
    id: "sup-005",
    name: "Protein Source Manufacturing",
    registrationNo: "201901034567",
    contactPerson: "Lim Boon Keat",
    email: "supply@proteinsource.com.my",
    phone: "+603-6677 8899",
    address: "Lot 88, Kawasan Perindustrian Shah Alam Seksyen 23, 40300 Shah Alam, Selangor",
    suppliedIngredients: ["Ikan Bilis Kering", "Udang Kering"],
    halalCertNo: null,
    halalCertBody: null,
    certStatus: "Expiring Soon",
    certExpiry: "2025-03-20",
    riskLevel: "Medium",
  },
];

// ── INGREDIENTS ─────────────────────────────────────────────
export const ingredients = [
  {
    id: "ing-001",
    name: "Beras Basmati",
    brand: "Mulia",
    supplierId: "sup-004",
    supplierName: "Mulia Rice Mill Sdn Bhd",
    countryOfOrigin: "Malaysia",
    category: "Grain",
    riskFlags: [],
    certStatus: "Valid",
    certExpiry: "2026-03-31",
    isCritical: false,
    linkedMenus: ["menu-001", "menu-002", "menu-003"],
  },
  {
    id: "ing-002",
    name: "Santan UHT",
    brand: "Puncak",
    supplierId: "sup-002",
    supplierName: "Puncak Dairy Industries Sdn Bhd",
    countryOfOrigin: "Malaysia",
    category: "Dairy",
    riskFlags: ["animal-derived"],
    certStatus: "Valid",
    certExpiry: "2026-06-30",
    isCritical: true,
    linkedMenus: ["menu-001", "menu-004"],
  },
  {
    id: "ing-003",
    name: "Rempah Nasi Lemak",
    brand: "Delima",
    supplierId: "sup-001",
    supplierName: "Delima Spices & Herbs Sdn Bhd",
    countryOfOrigin: "Malaysia",
    category: "Spice & Seasoning",
    riskFlags: ["flavoring"],
    certStatus: "Valid",
    certExpiry: "2025-12-31",
    isCritical: true,
    linkedMenus: ["menu-001"],
  },
  {
    id: "ing-004",
    name: "Ikan Bilis Kering",
    brand: "Protein Source",
    supplierId: "sup-005",
    supplierName: "Protein Source Manufacturing",
    countryOfOrigin: "Malaysia",
    category: "Seafood",
    riskFlags: ["animal-derived"],
    certStatus: "Expiring Soon",
    certExpiry: "2025-03-20",
    isCritical: true,
    linkedMenus: ["menu-001", "menu-005"],
  },
  {
    id: "ing-005",
    name: "Perisa Pandan",
    brand: "GlobalFood",
    supplierId: "sup-003",
    supplierName: "Global Food Ingredients Bhd",
    countryOfOrigin: "Malaysia",
    category: "Flavoring",
    riskFlags: ["flavoring", "alcohol"],
    certStatus: "Expired",
    certExpiry: "2024-12-31",
    isCritical: true,
    linkedMenus: ["menu-002", "menu-006"],
  },
  {
    id: "ing-006",
    name: "Stabiliser E471",
    brand: "GlobalFood",
    supplierId: "sup-003",
    supplierName: "Global Food Ingredients Bhd",
    countryOfOrigin: "Germany",
    category: "Food Additive",
    riskFlags: ["animal-derived", "gelatin"],
    certStatus: "Expired",
    certExpiry: "2024-12-31",
    isCritical: true,
    linkedMenus: ["menu-004"],
  },
  {
    id: "ing-007",
    name: "Cili Boh",
    brand: "Delima",
    supplierId: "sup-001",
    supplierName: "Delima Spices & Herbs Sdn Bhd",
    countryOfOrigin: "Malaysia",
    category: "Spice & Seasoning",
    riskFlags: [],
    certStatus: "Valid",
    certExpiry: "2025-12-31",
    isCritical: false,
    linkedMenus: ["menu-001", "menu-007"],
  },
  {
    id: "ing-008",
    name: "Beras Tempatan",
    brand: "Mulia",
    supplierId: "sup-004",
    supplierName: "Mulia Rice Mill Sdn Bhd",
    countryOfOrigin: "Malaysia",
    category: "Grain",
    riskFlags: [],
    certStatus: "Valid",
    certExpiry: "2026-03-31",
    isCritical: false,
    linkedMenus: ["menu-003"],
  },
  {
    id: "ing-009",
    name: "Santan Segar",
    brand: "Puncak",
    supplierId: "sup-002",
    supplierName: "Puncak Dairy Industries Sdn Bhd",
    countryOfOrigin: "Malaysia",
    category: "Dairy",
    riskFlags: ["animal-derived"],
    certStatus: "Valid",
    certExpiry: "2026-06-30",
    isCritical: true,
    linkedMenus: ["menu-001", "menu-008"],
  },
  {
    id: "ing-010",
    name: "Garam",
    brand: "Kimia",
    supplierId: null,
    supplierName: "Generic",
    countryOfOrigin: "Malaysia",
    category: "Seasoning",
    riskFlags: [],
    certStatus: "N/A",
    certExpiry: null,
    isCritical: false,
    linkedMenus: ["menu-001", "menu-002", "menu-003"],
  },
  {
    id: "ing-011",
    name: "Udang Kering",
    brand: "Protein Source",
    supplierId: "sup-005",
    supplierName: "Protein Source Manufacturing",
    countryOfOrigin: "Malaysia",
    category: "Seafood",
    riskFlags: ["animal-derived"],
    certStatus: "Expiring Soon",
    certExpiry: "2025-03-20",
    isCritical: true,
    linkedMenus: ["menu-005"],
  },
  {
    id: "ing-012",
    name: "Pewarna Makanan Merah",
    brand: "GlobalFood",
    supplierId: "sup-003",
    supplierName: "Global Food Ingredients Bhd",
    countryOfOrigin: "USA",
    category: "Food Additive",
    riskFlags: ["flavoring"],
    certStatus: "Expired",
    certExpiry: "2024-12-31",
    isCritical: true,
    linkedMenus: ["menu-006", "menu-007"],
  },
];

// ── MENUS ───────────────────────────────────────────────────
export const menus = [
  {
    id: "menu-001",
    name: "Nasi Lemak Classic",
    category: "Main Course",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    ingredients: ["ing-001", "ing-002", "ing-003", "ing-004", "ing-007", "ing-009", "ing-010"],
    readiness: "warning",
    readinessScore: 72,
    description: "Signature nasi lemak with sambal, ikan bilis, and egg",
  },
  {
    id: "menu-002",
    name: "Nasi Lemak Pandan",
    category: "Main Course",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    ingredients: ["ing-001", "ing-005", "ing-003", "ing-010"],
    readiness: "fail",
    readinessScore: 40,
    description: "Pandan-infused nasi lemak — contains ingredient with expired cert",
  },
  {
    id: "menu-003",
    name: "Nasi Putih",
    category: "Side",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    ingredients: ["ing-001", "ing-008", "ing-010"],
    readiness: "pass",
    readinessScore: 98,
    description: "Plain steamed rice",
  },
  {
    id: "menu-004",
    name: "Santan Kukus",
    category: "Dessert",
    locationId: "loc-002",
    locationName: "Central Kitchen – Petaling Jaya",
    ingredients: ["ing-002", "ing-006"],
    readiness: "fail",
    readinessScore: 30,
    description: "Coconut steamed dessert — ingredient E471 has expired halal cert",
  },
  {
    id: "menu-005",
    name: "Sambal Ikan Bilis",
    category: "Condiment",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    ingredients: ["ing-004", "ing-011", "ing-007"],
    readiness: "warning",
    readinessScore: 65,
    description: "Spicy sambal with dried anchovies and shrimp",
  },
  {
    id: "menu-006",
    name: "Pulut Serawa",
    category: "Dessert",
    locationId: "loc-002",
    locationName: "Central Kitchen – Petaling Jaya",
    ingredients: ["ing-005", "ing-012", "ing-009"],
    readiness: "fail",
    readinessScore: 25,
    description: "Sticky rice with pandan coconut sauce — multiple expired certs",
  },
  {
    id: "menu-007",
    name: "Sambal Tumis",
    category: "Condiment",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    ingredients: ["ing-007", "ing-012"],
    readiness: "warning",
    readinessScore: 60,
    description: "Cooked sambal — contains expired food colouring",
  },
  {
    id: "menu-008",
    name: "Pengat Pisang",
    category: "Dessert",
    locationId: "loc-003",
    locationName: "Kiosk – KLCC",
    ingredients: ["ing-009", "ing-010"],
    readiness: "pass",
    readinessScore: 95,
    description: "Banana in coconut milk dessert",
  },
];

// ── DOCUMENTS ───────────────────────────────────────────────
export const documents = [
  {
    id: "doc-001",
    name: "SSM Certificate of Incorporation",
    type: "Company Registration",
    linkedTo: "Company",
    linkedId: "comp-001",
    status: "Valid",
    uploadDate: "2023-06-10",
    expiryDate: null,
    uploadedBy: "Ahmad Faris",
  },
  {
    id: "doc-002",
    name: "Business Licence – Main Outlet",
    type: "Business Licence",
    linkedTo: "Location",
    linkedId: "loc-001",
    status: "Valid",
    uploadDate: "2023-07-01",
    expiryDate: "2025-12-31",
    uploadedBy: "Ahmad Faris",
  },
  {
    id: "doc-003",
    name: "Food Premise Registration – Main Outlet",
    type: "Food Premise Registration",
    linkedTo: "Location",
    linkedId: "loc-001",
    status: "Valid",
    uploadDate: "2023-07-05",
    expiryDate: "2025-12-31",
    uploadedBy: "Siti Aisyah",
  },
  {
    id: "doc-004",
    name: "Halal PIC Certificate – Ahmad Faris",
    type: "Halal Training Certificate",
    linkedTo: "Employee",
    linkedId: "emp-001",
    status: "Valid",
    uploadDate: "2023-08-15",
    expiryDate: "2025-12-31",
    uploadedBy: "Ahmad Faris",
  },
  {
    id: "doc-005",
    name: "Halal PIC Certificate – Muhammad Haziq",
    type: "Halal Training Certificate",
    linkedTo: "Employee",
    linkedId: "emp-003",
    status: "Valid",
    uploadDate: "2024-03-20",
    expiryDate: "2026-03-31",
    uploadedBy: "Nurul Hidayah",
  },
  {
    id: "doc-006",
    name: "Halal Executive Certificate – Nurul Hidayah",
    type: "Halal Executive Certificate",
    linkedTo: "Employee",
    linkedId: "emp-004",
    status: "Expiring Soon",
    uploadDate: "2023-03-15",
    expiryDate: "2025-03-15",
    uploadedBy: "Nurul Hidayah",
  },
  {
    id: "doc-007",
    name: "Supplier Halal Cert – Delima Spices",
    type: "Supplier Halal Certificate",
    linkedTo: "Supplier",
    linkedId: "sup-001",
    status: "Valid",
    uploadDate: "2022-12-01",
    expiryDate: "2025-12-31",
    uploadedBy: "Nurul Hidayah",
  },
  {
    id: "doc-008",
    name: "Supplier Halal Cert – Global Food Ingredients",
    type: "Supplier Halal Certificate",
    linkedTo: "Supplier",
    linkedId: "sup-003",
    status: "Expired",
    uploadDate: "2021-12-01",
    expiryDate: "2024-12-31",
    uploadedBy: "Nurul Hidayah",
  },
  {
    id: "doc-009",
    name: "Ingredient Spec – Stabiliser E471",
    type: "Ingredient Specification",
    linkedTo: "Ingredient",
    linkedId: "ing-006",
    status: "Expired",
    uploadDate: "2021-11-15",
    expiryDate: "2024-12-31",
    uploadedBy: "Nurul Hidayah",
  },
  {
    id: "doc-010",
    name: "Cleaning & Sanitation SOP",
    type: "SOP",
    linkedTo: "Location",
    linkedId: "loc-001",
    status: "Valid",
    uploadDate: "2023-09-01",
    expiryDate: null,
    uploadedBy: "Siti Aisyah",
  },
  {
    id: "doc-011",
    name: "Menu List – Main Outlet",
    type: "Menu List",
    linkedTo: "Application",
    linkedId: "APP-001",
    status: "Valid",
    uploadDate: "2024-01-10",
    expiryDate: null,
    uploadedBy: "Siti Aisyah",
  },
  {
    id: "doc-012",
    name: "Business Licence – Central Kitchen",
    type: "Business Licence",
    linkedTo: "Location",
    linkedId: "loc-002",
    status: "Expiring Soon",
    uploadDate: "2023-09-01",
    expiryDate: "2025-03-01",
    uploadedBy: "Ahmad Faris",
  },
  {
    id: "doc-013",
    name: "Food Handler Cert – Rosmawati",
    type: "Food Handler Certificate",
    linkedTo: "Employee",
    linkedId: "emp-006",
    status: "Expiring Soon",
    uploadDate: "2023-09-15",
    expiryDate: "2025-03-15",
    uploadedBy: "Siti Aisyah",
  },
  {
    id: "doc-014",
    name: "Pest Control Record – Q4 2024",
    type: "Pest Control Record",
    linkedTo: "Location",
    linkedId: "loc-001",
    status: "Valid",
    uploadDate: "2024-12-31",
    expiryDate: "2025-12-31",
    uploadedBy: "Ahmad Faris",
  },
  {
    id: "doc-015",
    name: "Internal Halal Committee Appointment Letter",
    type: "Appointment Letter",
    linkedTo: "Company",
    linkedId: "comp-001",
    status: "Valid",
    uploadDate: "2023-07-15",
    expiryDate: null,
    uploadedBy: "Ahmad Faris",
  },
];

// ── APPLICATIONS ─────────────────────────────────────────────
export const applications = [
  {
    id: "APP-001",
    referenceNo: "APP-2024-001",
    type: "New Application",
    scheme: "Food Premises",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    picId: "emp-001",
    picName: "Ahmad Faris bin Abdullah",
    status: "In Review",
    readinessScore: 78,
    blockingIssues: 4,
    warnings: 7,
    submittedDate: "2024-12-15",
    createdDate: "2024-11-01",
    lastUpdated: "2025-01-20",
    includedMenus: ["menu-001", "menu-002", "menu-003", "menu-005", "menu-007"],
    myeHalalRefNo: null,
  },
  {
    id: "APP-002",
    referenceNo: "APP-2025-002",
    type: "New Application",
    scheme: "Food Premises",
    locationId: "loc-002",
    locationName: "Central Kitchen – Petaling Jaya",
    picId: "emp-003",
    picName: "Muhammad Haziq bin Rosli",
    status: "In Progress",
    readinessScore: 45,
    blockingIssues: 9,
    warnings: 12,
    submittedDate: null,
    createdDate: "2025-01-15",
    lastUpdated: "2025-02-10",
    includedMenus: ["menu-004", "menu-006"],
    myeHalalRefNo: null,
  },
  {
    id: "APP-003",
    referenceNo: "APP-2023-003",
    type: "Renewal",
    scheme: "Food Premises",
    locationId: "loc-001",
    locationName: "Main Outlet – Bukit Bintang",
    picId: "emp-001",
    picName: "Ahmad Faris bin Abdullah",
    status: "Approved",
    readinessScore: 100,
    blockingIssues: 0,
    warnings: 0,
    submittedDate: "2023-09-01",
    createdDate: "2023-08-01",
    lastUpdated: "2023-11-30",
    includedMenus: ["menu-001", "menu-003"],
    myeHalalRefNo: "MYH-2023-FP-00512",
  },
];

// ── REQUIREMENT CHECKLIST (for APP-001) ─────────────────────
export const requirementResults = [
  // Document Requirements
  { id: "req-001", category: "Document", name: "SSM / Company Registration", severity: "Blocking", status: "passed", note: null },
  { id: "req-002", category: "Document", name: "Food Premise Registration Certificate", severity: "Blocking", status: "passed", note: null },
  { id: "req-003", category: "Document", name: "Business Licence (Current Year)", severity: "Blocking", status: "passed", note: null },
  { id: "req-004", category: "Document", name: "Menu List (Certified Copy)", severity: "Blocking", status: "passed", note: null },
  { id: "req-005", category: "Document", name: "Cleaning & Sanitation SOP", severity: "Warning", status: "passed", note: null },
  { id: "req-006", category: "Document", name: "Pest Control Record (Last 6 Months)", severity: "Warning", status: "passed", note: null },
  { id: "req-007", category: "Document", name: "Internal Halal Committee Appointment Letter", severity: "Blocking", status: "passed", note: null },
  { id: "req-008", category: "Document", name: "Process Flowchart", severity: "Recommended", status: "failed", note: "Document not uploaded" },

  // Employee Requirements
  { id: "req-009", category: "Employee", name: "At Least 1 Muslim Malaysian Permanent Employee", severity: "Blocking", status: "passed", note: null },
  { id: "req-010", category: "Employee", name: "Halal PIC Assigned and Certified", severity: "Blocking", status: "passed", note: null },
  { id: "req-011", category: "Employee", name: "Halal Supervisor Assigned", severity: "Warning", status: "passed", note: null },
  { id: "req-012", category: "Employee", name: "All Food Handlers Have Valid Certs", severity: "Warning", status: "warning", note: "Rosmawati's food handler cert expiring in 23 days" },
  { id: "req-013", category: "Employee", name: "Halal Executive Certificate (Nurul Hidayah)", severity: "Warning", status: "warning", note: "Certificate expiring on 15 Mar 2025" },

  // Ingredient Requirements
  { id: "req-014", category: "Ingredient", name: "All Critical Ingredients Have Halal Evidence", severity: "Blocking", status: "failed", note: "Perisa Pandan cert expired, Stabiliser E471 cert expired" },
  { id: "req-015", category: "Ingredient", name: "No Alcohol-Based Flavoring Without Approved Exception", severity: "Blocking", status: "failed", note: "Perisa Pandan flagged as alcohol-based (supplier cert expired)" },
  { id: "req-016", category: "Ingredient", name: "Animal-Derived Ingredients Properly Certified", severity: "Blocking", status: "warning", note: "Ikan Bilis cert expiring in 28 days" },
  { id: "req-017", category: "Ingredient", name: "All Ingredients Have Supplier Data", severity: "Warning", status: "passed", note: null },

  // Supplier Requirements
  { id: "req-018", category: "Supplier", name: "All Suppliers Have Valid Halal Cert", severity: "Blocking", status: "failed", note: "Global Food Ingredients Bhd cert expired 31 Dec 2024" },
  { id: "req-019", category: "Supplier", name: "Supplier Certs Not Expiring Within 30 Days", severity: "Warning", status: "warning", note: "Protein Source Manufacturing cert expiring 20 Mar 2025" },
  { id: "req-020", category: "Supplier", name: "Supplier Contact Information Complete", severity: "Recommended", status: "passed", note: null },

  // Location Requirements
  { id: "req-021", category: "Location", name: "Location Operating ≥ 3 Months Before Application", severity: "Blocking", status: "passed", note: null },
  { id: "req-022", category: "Location", name: "Local Authority Licence Valid", severity: "Blocking", status: "passed", note: null },
  { id: "req-023", category: "Location", name: "No Najis/Haram Cross-Contamination Risk", severity: "Blocking", status: "failed", note: "Ingredient with expired halal status used in active menu" },
];

// ── TASKS ────────────────────────────────────────────────────
export const tasks = [
  {
    id: "task-001",
    title: "Renew Halal Cert for Global Food Ingredients",
    description: "Supplier certificate expired on 31 Dec 2024. Renew or replace supplier urgently.",
    module: "Supplier",
    linkedId: "sup-003",
    priority: "High",
    status: "Open",
    dueDate: "2025-02-28",
    assignedTo: "user-002",
    assignedName: "Nurul Hidayah",
    source: "Requirement Engine",
    createdDate: "2025-01-15",
  },
  {
    id: "task-002",
    title: "Upload Process Flowchart for Main Outlet",
    description: "Missing required document for APP-001 application package.",
    module: "Document",
    linkedId: "APP-001",
    priority: "High",
    status: "Open",
    dueDate: "2025-02-25",
    assignedTo: "user-003",
    assignedName: "Siti Aisyah",
    source: "Requirement Engine",
    createdDate: "2025-01-15",
  },
  {
    id: "task-003",
    title: "Replace Perisa Pandan with Halal-Certified Alternative",
    description: "Perisa Pandan (ing-005) has expired halal cert. Affects Nasi Lemak Pandan and Pulut Serawa.",
    module: "Ingredient",
    linkedId: "ing-005",
    priority: "High",
    status: "In Progress",
    dueDate: "2025-03-01",
    assignedTo: "user-002",
    assignedName: "Nurul Hidayah",
    source: "AI + Requirement Engine",
    createdDate: "2025-01-20",
  },
  {
    id: "task-004",
    title: "Renew Halal Executive Cert – Nurul Hidayah",
    description: "Certificate expires 15 Mar 2025. Register for renewal at JAKIM.",
    module: "Employee",
    linkedId: "emp-004",
    priority: "High",
    status: "Open",
    dueDate: "2025-03-01",
    assignedTo: "user-001",
    assignedName: "Ahmad Faris",
    source: "System",
    createdDate: "2025-01-10",
  },
  {
    id: "task-005",
    title: "Renew Food Handler Cert – Rosmawati",
    description: "Certificate expires 15 Mar 2025. Coordinate with DBKL/MOH clinic.",
    module: "Employee",
    linkedId: "emp-006",
    priority: "Medium",
    status: "Open",
    dueDate: "2025-03-10",
    assignedTo: "user-003",
    assignedName: "Siti Aisyah",
    source: "System",
    createdDate: "2025-01-10",
  },
  {
    id: "task-006",
    title: "Confirm Protein Source Manufacturing Cert Renewal",
    description: "Supplier cert expiring 20 Mar 2025. Confirm renewal status.",
    module: "Supplier",
    linkedId: "sup-005",
    priority: "Medium",
    status: "In Progress",
    dueDate: "2025-03-15",
    assignedTo: "user-002",
    assignedName: "Nurul Hidayah",
    source: "System",
    createdDate: "2025-01-20",
  },
  {
    id: "task-007",
    title: "Renew Business Licence – Central Kitchen",
    description: "Licence expires 1 Mar 2025. Submit renewal to MBPJ.",
    module: "Document",
    linkedId: "loc-002",
    priority: "High",
    status: "Open",
    dueDate: "2025-02-20",
    assignedTo: "user-001",
    assignedName: "Ahmad Faris",
    source: "System",
    createdDate: "2025-01-05",
  },
  {
    id: "task-008",
    title: "Review OCR Extraction – Supplier Cert Puncak Dairy",
    description: "OCR extracted cert data pending review before it can be used as verified evidence.",
    module: "Document",
    linkedId: "doc-007",
    priority: "Low",
    status: "Open",
    dueDate: "2025-02-28",
    assignedTo: "user-002",
    assignedName: "Nurul Hidayah",
    source: "AI",
    createdDate: "2025-02-01",
  },
  {
    id: "task-009",
    title: "Complete Scope Selection for APP-002",
    description: "Application APP-002 draft is missing menu scope — please complete in the wizard.",
    module: "Application",
    linkedId: "APP-002",
    priority: "Medium",
    status: "Open",
    dueDate: "2025-03-01",
    assignedTo: "user-003",
    assignedName: "Siti Aisyah",
    source: "User",
    createdDate: "2025-01-15",
  },
  {
    id: "task-010",
    title: "Submit Typhoid Vaccination Record – Priya",
    description: "Missing typhoid vaccination document for Priya Ramasamy.",
    module: "Employee",
    linkedId: "emp-008",
    priority: "Medium",
    status: "Open",
    dueDate: "2025-03-15",
    assignedTo: "user-003",
    assignedName: "Siti Aisyah",
    source: "Requirement Engine",
    createdDate: "2025-01-25",
  },
  {
    id: "task-011",
    title: "Upload Ingredient Spec for E471 Alternative",
    description: "Replacement ingredient for E471 needs spec sheet upload.",
    module: "Ingredient",
    linkedId: "ing-006",
    priority: "High",
    status: "In Progress",
    dueDate: "2025-03-05",
    assignedTo: "user-002",
    assignedName: "Nurul Hidayah",
    source: "User",
    createdDate: "2025-02-05",
  },
  {
    id: "task-012",
    title: "Prepare Submission Package for APP-001",
    description: "Compile all documents and complete final checklist before export.",
    module: "Application",
    linkedId: "APP-001",
    priority: "High",
    status: "Open",
    dueDate: "2025-03-31",
    assignedTo: "user-001",
    assignedName: "Ahmad Faris",
    source: "User",
    createdDate: "2025-02-10",
  },
];

// ── ACTIVITY LOG ─────────────────────────────────────────────
export const activityLog = [
  {
    id: "log-001",
    actor: "Nurul Hidayah",
    action: "Uploaded supplier halal certificate",
    module: "Supplier",
    record: "Delima Spices & Herbs Sdn Bhd",
    timestamp: "2025-02-18T10:23:00",
    source: "user",
  },
  {
    id: "log-002",
    actor: "AI Assistant",
    action: "Generated readiness recommendations for APP-001",
    module: "Application",
    record: "APP-2024-001",
    timestamp: "2025-02-18T09:15:00",
    source: "ai",
  },
  {
    id: "log-003",
    actor: "Requirement Engine",
    action: "Re-evaluated APP-001 — score updated from 75% to 78%",
    module: "Application",
    record: "APP-2024-001",
    timestamp: "2025-02-17T16:45:00",
    source: "system",
  },
  {
    id: "log-004",
    actor: "Siti Aisyah",
    action: "Updated menu: Nasi Lemak Classic — added Santan Segar ingredient",
    module: "Menu",
    record: "Nasi Lemak Classic",
    timestamp: "2025-02-17T14:30:00",
    source: "user",
  },
  {
    id: "log-005",
    actor: "Ahmad Faris",
    action: "Accepted AI recommendation: Replace Perisa Pandan",
    module: "AI Assistant",
    record: "APP-2024-001",
    timestamp: "2025-02-16T11:00:00",
    source: "ai",
  },
  {
    id: "log-006",
    actor: "System",
    action: "Alert: Global Food Ingredients Bhd cert expired",
    module: "Supplier",
    record: "Global Food Ingredients Bhd",
    timestamp: "2025-01-01T00:01:00",
    source: "system",
  },
  {
    id: "log-007",
    actor: "Ahmad Faris",
    action: "Created Application APP-2025-002 for Central Kitchen",
    module: "Application",
    record: "APP-2025-002",
    timestamp: "2025-01-15T09:00:00",
    source: "user",
  },
  {
    id: "log-008",
    actor: "Nurul Hidayah",
    action: "Assigned Halal PIC: Muhammad Haziq for Central Kitchen",
    module: "Employee",
    record: "Muhammad Haziq bin Rosli",
    timestamp: "2024-12-20T15:30:00",
    source: "user",
  },
];

// ── AI CHAT MESSAGES ─────────────────────────────────────────
export const aiChatMessages = [
  {
    id: "msg-001",
    role: "user",
    content: "What documents are missing for my APP-001 application?",
    timestamp: "2025-02-18T09:00:00",
  },
  {
    id: "msg-002",
    role: "assistant",
    content: `Based on your current readiness check for **APP-2024-001 (Main Outlet – Bukit Bintang)**, here are the missing or problematic documents:\n\n**Blocking Issues:**\n1. 🔴 **Process Flowchart** — Not uploaded. This is required for Food Premises applications.\n2. 🔴 **Global Food Ingredients Halal Certificate** — Expired 31 Dec 2024. Affects Perisa Pandan and Stabiliser E471.\n\n**Expiring Soon:**\n3. ⚠️ **Halal Executive Certificate (Nurul Hidayah)** — Expires 15 Mar 2025 (23 days)\n4. ⚠️ **Food Handler Cert (Rosmawati)** — Expires 15 Mar 2025 (23 days)\n5. ⚠️ **Business Licence – Central Kitchen** — Expires 1 Mar 2025\n\nI recommend addressing the blocking issues first. Would you like me to create tasks for each of these?`,
    timestamp: "2025-02-18T09:00:30",
  },
  {
    id: "msg-003",
    role: "user",
    content: "Yes, create tasks for the blocking issues. Also, can you explain why Perisa Pandan is flagged?",
    timestamp: "2025-02-18T09:01:15",
  },
  {
    id: "msg-004",
    role: "assistant",
    content: `I've created 2 tasks for the blocking issues:\n- ✅ **Task created**: "Renew Halal Cert for Global Food Ingredients" (High priority, due 28 Feb)\n- ✅ **Task created**: "Upload Process Flowchart for Main Outlet" (High priority, due 25 Feb)\n\n---\n\n**Why Perisa Pandan is flagged:**\n\nPerisa Pandan (Flavoring) is considered a **critical ingredient** under JAKIM's Food Premises guidelines because:\n1. It is a flavoring agent — these must be proven halal as they may contain alcohol-based carriers or animal-derived compounds\n2. The current halal certificate from **Global Food Ingredients Bhd** expired on 31 Dec 2024\n3. Additionally, this ingredient has an **alcohol risk flag** — meaning it was previously identified as potentially using an alcohol solvent in the flavoring process\n\n**Recommendation:** Contact Global Food Ingredients for an updated cert, OR source an alternative pandan flavoring from a JAKIM-certified supplier. I can help you search for alternative certified suppliers.`,
    timestamp: "2025-02-18T09:01:45",
  },
];

// ── AI RECOMMENDATIONS ────────────────────────────────────────
export const aiRecommendations = [
  {
    id: "rec-001",
    title: "Replace Global Food Ingredients as Supplier",
    description: "Supplier certificate has expired and affects 3 critical ingredients. Consider switching to a JAKIM-certified alternative supplier.",
    priority: "High",
    linkedModule: "Supplier",
    status: "pending",
    applicationId: "APP-001",
  },
  {
    id: "rec-002",
    title: "Draft Cleaning SOP for Central Kitchen",
    description: "Central Kitchen application (APP-002) is missing a Cleaning & Sanitation SOP. I can draft a template based on JAKIM MS 1500:2019 requirements.",
    priority: "Medium",
    linkedModule: "Document",
    status: "pending",
    applicationId: "APP-002",
  },
  {
    id: "rec-003",
    title: "Register Nurul Hidayah for Halal Executive Renewal",
    description: "Certificate expires in 23 days. JAKIM's next scheduled course is 8 Mar 2025 in KL. Register now to avoid disruption.",
    priority: "High",
    linkedModule: "Employee",
    status: "pending",
    applicationId: "APP-001",
  },
];

// ── INVOICES ─────────────────────────────────────────────────
export const invoices = [
  { id: "INV-2025-002", date: "2025-02-01", amount: "RM 299.00", status: "Paid", plan: "Pro" },
  { id: "INV-2025-001", date: "2025-01-01", amount: "RM 299.00", status: "Paid", plan: "Pro" },
  { id: "INV-2024-012", date: "2024-12-01", amount: "RM 299.00", status: "Paid", plan: "Pro" },
  { id: "INV-2024-011", date: "2024-11-01", amount: "RM 299.00", status: "Paid", plan: "Pro" },
];

// ── SUMMARY STATS (derived) ──────────────────────────────────
export const dashboardStats = {
  activeApplications: 3,
  readinessScore: 78,
  openTasks: tasks.filter(t => t.status === "Open").length,
  expiringSoon: documents.filter(d => d.status === "Expiring Soon").length,
};
